
//Internal EEPROM locations for user settings
#define LOCATION_MASS_UNITS                     0x01
#define LOCATION_CALIBRATION_FACTOR_MSB         (LOCATION_MASS_UNITS + 1)
#define LOCATION_CALIBRATION_FACTOR_MIDHIGH     (LOCATION_MASS_UNITS + 2)
#define LOCATION_CALIBRATION_FACTOR_MIDLOW      (LOCATION_MASS_UNITS + 3)
#define LOCATION_CALIBRATION_FACTOR_LSB         (LOCATION_MASS_UNITS + 4)
#define LOCATION_TARE_POINT_MSB                 (LOCATION_MASS_UNITS + 5)
#define LOCATION_TARE_POINT_MIDHIGH             (LOCATION_MASS_UNITS + 6)
#define LOCATION_TARE_POINT_MIDLOW              (LOCATION_MASS_UNITS + 7)
#define LOCATION_TARE_POINT_LSB                 (LOCATION_MASS_UNITS + 8)
#define LOCATION_DECIMAL_PLACES                 (LOCATION_MASS_UNITS + 9)
#define LOCATION_AVERAGE_AMOUNT                 (LOCATION_MASS_UNITS + 10)
#define LOCATION_SERIAL_TRIGGER_ENABLE          (LOCATION_MASS_UNITS + 11)
#define LOCATION_WIRELESS_PASSWORD_MSB			(LOCATION_MASS_UNITS + 12)
#define LOCATION_WIRELESS_PASSWORD_MIDHIGH		(LOCATION_MASS_UNITS + 13)
#define LOCATION_WIRELESS_PASSWORD_MIDLOW		(LOCATION_MASS_UNITS + 14)
#define LOCATION_WIRELESS_PASSWORD_LSB			(LOCATION_MASS_UNITS + 15)

#define UNITS_KG  0
#define UNITS_LBS 1
#define UNITS_GRAMS 2
#define UNITS_MILLI_GRAMS 3